### ISSUE TITLE
Invalid docker command in readme

### ISSUE THREAD

**Issue by qarmin** [MGlolenstine/gtk4-cross#14]
```
docker run -ti -v `pwd`:/mnt gtk4-cross-rust
```
is invalid and doesn't work in my OS.
This command works fine
```
docker run -ti -v `pwd`:/mnt mglolenstine/gtk4-cross:rust-gtk-4.6
```

**Comment by MGlolenstine** [comment]
The first command fetches the image from the local repository, so you would have to build it before running that command.
The second one pulls it from the DockerHub.
