### ISSUE TITLE
Cannot package project with multiple workspaces

### ISSUE THREAD

**Issue by qarmin** [MGlolenstine/gtk4-cross#15]
I trying to pack https://github.com/qarmin/czkawka, but for now I have problem with package command
after building with 
```
build
```
I tried to execute
```
package/target/x86_64-pc-windows-gnu/release/czkawka_gui.exe 
```
but it just create one file and printed this errors:
```
mkdir: cannot create directory ‘package’: Not a directory
mkdir: cannot create directory ‘package’: Not a directory
mkdir: cannot create directory ‘package’: Not a directory
```

**Comment by MGlolenstine** [comment]
I'll take a look.

**Comment by MGlolenstine** [comment]
After switching to the pelld branch and building the app, all dependencies are met, but the application crashes upon opening.
The application seems to launch correctly, but it seems that some Rust code crashes the app after the launch.
After commenting the `#![windows_subsystem = "windows"]` I was able to see the crash log.
```
PS C:\Users\asd\Desktop\package\package> .\czkawka_gui.exe
Gsk-Message: 20:41:15.590: Failed to realize renderer of type 'GskGLRenderer' for surface 'GdkWin32Toplevel': No GL implementation is available

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { domain: gdk-pixbuf-error-quark, code: 3, message: "Unrecognized image file format" }', czkawka_gui/src/help_functions.rs:856:67
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
I will merge the pelld update tomorrow, so that you can reproduce it yourself.

**Comment by qarmin** [comment]
I already packed manually app basing on GTK 3 version, so I know that this crash is related to missing pixbuf loaders
Working version of app is available here - https://github.com/qarmin/czkawka/files/8840608/package.zip

It contains additional `lib/gdk-pixbuf-2.0/2.10.0` folder with loaders, so copying it should fix issue.
Some loaders are available inside docker image
```
[root@6e43893f292f /]# find . | grep libpixbufloader
./usr/lib64/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-jxl.so
./usr/x86_64-w64-mingw32/sys-root/mingw/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-ani.dll
./usr/x86_64-w64-mingw32/sys-root/mingw/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-pnm.dll
./usr/x86_64-w64-mingw32/sys-root/mingw/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-icns.dll
./usr/x86_64-w64-mingw32/sys-root/mingw/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.dll
./usr/x86_64-w64-mingw32/sys-root/mingw/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.dll.a
./usr/x86_64-w64-mingw32/sys-root/mingw/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-xpm.dll
./usr/x86_64-w64-mingw32/sys-root/mingw/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-xbm.dll
./usr/x86_64-w64-mingw32/sys-root/mingw/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-tga.dll
./usr/x86_64-w64-mingw32/sys-root/mingw/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-qtif.dll
[root@6e43893f292f /]# 
```

**Comment by MGlolenstine** [comment]
Copying the loaders into a GTK4 package doesn't seem to work. I get the same error.
I grabbed the `lib` folder and copied it into the same place inside of the GTK build.
