### ISSUE TITLE
Add support for gtksourceview5

### ISSUE THREAD

**Issue by Stefan99353** [MGlolenstine/gtk4-cross#24]
Since Fedora does not have gtksourceview5 in its repos it needs to be compiled.
I could not get that to work, but also could not try for very loing.

**Comment by MGlolenstine** [comment]
Fedora 35 does seem to package `gtksourceview5`, admittedly not in the official repositories, but in the `Updates` one.
To install it, you could add the repository to your docker image and install the package or the RPM from [here](https://fedora.pkgs.org/35/fedora-updates-x86_64/gtksourceview5-devel-5.3.2-2.fc35.x86_64.rpm.html).

The `gtk4-cross` images will be updated to Fedora 37 shortly and should add `gtksourceview5` to the official repositories, removing this overhead.
