### ISSUE TITLE
Publish also to github container registry

### ISSUE THREAD

**Issue by 13hannes11** [MGlolenstine/gtk4-cross#5]
I think it would be good to have the images not only published on Dockerhub but also on the Github container registry.

**Comment by 13hannes11** [comment]
I have one script that already pushes to the Github container registry, maybe this can be a starting point:

https://github.com/13hannes11/ics-proxy/blob/main/.github/workflows/build-push-tagged.yml

**Comment by MGlolenstine** [comment]
Would this work for you? https://github.com/users/mglolenstine/packages/container/package/gtk4-cross

**Comment by 13hannes11** [comment]
Yes perfect!
